FROM ubuntu:20.04 as halide-runtime

WORKDIR /halide

RUN set -eux && \
  apt update && \
  apt install -y wget && \
  wget https://github.com/halide/Halide/releases/download/v12.0.1/Halide-12.0.1-x86-64-linux-5dabcaa9effca1067f907f6c8ea212f3d2b1d99a.tar.gz && \
  tar xzf Halide-12.0.1-x86-64-linux-5dabcaa9effca1067f907f6c8ea212f3d2b1d99a.tar.gz && \
  rm Halide-12.0.1-x86-64-linux-5dabcaa9effca1067f907f6c8ea212f3d2b1d99a.tar.gz && \
  mv Halide-12.0.1-x86-64-linux Halide-Runtime

RUN set -eux && \
  apt update && \
  apt install -y clang g++ binutils libpng-dev libjpeg-dev

COPY docker-entrypoint.generator.sh /usr/local/bin/docker-entrypoint.generator.sh
ENTRYPOINT [ "docker-entrypoint.generator.sh" ]
