FROM ubuntu:20.04 as halide-runtime

WORKDIR /halide

RUN set -eux && \
  apt update && \
  apt install -y wget clang g++ binutils libpng-dev libjpeg-dev && \
  wget https://github.com/halide/Halide/releases/download/v13.0.1/Halide-13.0.1-x86-64-linux-fb39d7e3149c0ee1e848bb9957be2ea18765c35d.tar.gz && \
  tar xzf Halide-13.0.1-x86-64-linux-fb39d7e3149c0ee1e848bb9957be2ea18765c35d.tar.gz && \
  rm Halide-13.0.1-x86-64-linux-fb39d7e3149c0ee1e848bb9957be2ea18765c35d.tar.gz && \
  mv Halide-13.0.1-x86-64-linux Halide-Runtime

COPY docker-entrypoint.generator.sh /usr/local/bin/docker-entrypoint.generator.sh
ENTRYPOINT [ "docker-entrypoint.generator.sh" ]
